// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MusicBeePlugin.API11
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[DebuggerStepThrough]
public partial class Bookmark
{
    
        public Child Entry { get; set; }
        public long Position { get; set; }
        public string Username { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Changed { get; set; }
    
    public Bookmark()
    {
        Entry = new Child();
    }
}
}
#pragma warning restore
