// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MusicBeePlugin.API11
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[DebuggerStepThrough]
public partial class Child
{
    
        public string Id { get; set; }
        public string Parent { get; set; }
        public bool IsDir { get; set; }
        public string Title { get; set; }
        public string Album { get; set; }
        public string Artist { get; set; }
        public int Track { get; set; }
        public int Year { get; set; }
        public string Genre { get; set; }
        public string CoverArt { get; set; }
        public long Size { get; set; }
        public string ContentType { get; set; }
        public string Suffix { get; set; }
        public string TranscodedContentType { get; set; }
        public string TranscodedSuffix { get; set; }
        public int Duration { get; set; }
        public int BitRate { get; set; }
        public string Path { get; set; }
        public bool IsVideo { get; set; }
        public int UserRating { get; set; }
        public double AverageRating { get; set; }
        public int DiscNumber { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Starred { get; set; }
        public string AlbumId { get; set; }
        public string ArtistId { get; set; }
        public MediaType Type { get; set; }
        public long BookmarkPosition { get; set; }
}
}
#pragma warning restore
