// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MusicBeePlugin.API11
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[DebuggerStepThrough]
public partial class Indexes
{
    
        public List<Artist> Shortcut { get; set; }
        public List<Index> Index { get; set; }
        public List<Child> Child { get; set; }
        public long LastModified { get; set; }
        public string IgnoredArticles { get; set; }
    
    public Indexes()
    {
        Child = new List<Child>();
        Index = new List<Index>();
        Shortcut = new List<Artist>();
    }
}
}
#pragma warning restore
