// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MusicBeePlugin.API11
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

public enum ItemChoiceType
{
    
    /// <remarks/>
    album,
    
    /// <remarks/>
    albumList,
    
    /// <remarks/>
    albumList2,
    
    /// <remarks/>
    artist,
    
    /// <remarks/>
    artistInfo,
    
    /// <remarks/>
    artistInfo2,
    
    /// <remarks/>
    artists,
    
    /// <remarks/>
    bookmarks,
    
    /// <remarks/>
    chatMessages,
    
    /// <remarks/>
    directory,
    
    /// <remarks/>
    error,
    
    /// <remarks/>
    genres,
    
    /// <remarks/>
    indexes,
    
    /// <remarks/>
    internetRadioStations,
    
    /// <remarks/>
    jukeboxPlaylist,
    
    /// <remarks/>
    jukeboxStatus,
    
    /// <remarks/>
    license,
    
    /// <remarks/>
    lyrics,
    
    /// <remarks/>
    musicFolders,
    
    /// <remarks/>
    nowPlaying,
    
    /// <remarks/>
    playlist,
    
    /// <remarks/>
    playlists,
    
    /// <remarks/>
    podcasts,
    
    /// <remarks/>
    randomSongs,
    
    /// <remarks/>
    searchResult,
    
    /// <remarks/>
    searchResult2,
    
    /// <remarks/>
    searchResult3,
    
    /// <remarks/>
    shares,
    
    /// <remarks/>
    similarSongs,
    
    /// <remarks/>
    similarSongs2,
    
    /// <remarks/>
    song,
    
    /// <remarks/>
    songsByGenre,
    
    /// <remarks/>
    starred,
    
    /// <remarks/>
    starred2,
    
    /// <remarks/>
    user,
    
    /// <remarks/>
    users,
    
    /// <remarks/>
    videos,
}
}
#pragma warning restore
