// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MusicBeePlugin.API11
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[DebuggerStepThrough]
public partial class JukeboxPlaylist : JukeboxStatus
{
    
        public List<Child> Entry { get; set; }
    
    public JukeboxPlaylist()
    {
        Entry = new List<Child>();
    }
}
}
#pragma warning restore
