// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MusicBeePlugin.API11
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using Newtonsoft.Json;
using System.IO;
using System.Text;
using System.Xml;
using System.Collections.Generic;

public enum MediaType
{
    
    /// <remarks/>
    music,
    
    /// <remarks/>
    podcast,
    
    /// <remarks/>
    audiobook,
    
    /// <remarks/>
    video,
}
}
#pragma warning restore
