// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MusicBeePlugin.API11
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[DebuggerStepThrough]
public partial class PodcastChannel
{
    
        public List<PodcastEpisode> Episode { get; set; }
        public string Id { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public PodcastStatus Status { get; set; }
        public string ErrorMessage { get; set; }
    
    public PodcastChannel()
    {
        Episode = new List<PodcastEpisode>();
    }
}
}
#pragma warning restore
