// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MusicBeePlugin.API11
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[DebuggerStepThrough]
public partial class Share
{
    
        public List<Child> Entry { get; set; }
        public string Id { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public string Username { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Expires { get; set; }
        public System.DateTime LastVisited { get; set; }
        public int VisitCount { get; set; }
    
    public Share()
    {
        Entry = new List<Child>();
    }
}
}
#pragma warning restore
