// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MusicBeePlugin.API11
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.Xml;
using System.Collections.Generic;

[DebuggerStepThrough]
public partial class User
{
    
        public string Username { get; set; }
        public string Email { get; set; }
        public bool ScrobblingEnabled { get; set; }
        public bool AdminRole { get; set; }
        public bool SettingsRole { get; set; }
        public bool DownloadRole { get; set; }
        public bool UploadRole { get; set; }
        public bool PlaylistRole { get; set; }
        public bool CoverArtRole { get; set; }
        public bool CommentRole { get; set; }
        public bool PodcastRole { get; set; }
        public bool StreamRole { get; set; }
        public bool JukeboxRole { get; set; }
        public bool ShareRole { get; set; }
}
}
#pragma warning restore
