// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace MusicBeePlugin.API12
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.IO;
using System.Text;
using System.Xml;
using System.Collections.Generic;

public enum PodcastStatus
{
    
    /// <remarks/>
    @new,
    
    /// <remarks/>
    downloading,
    
    /// <remarks/>
    completed,
    
    /// <remarks/>
    error,
    
    /// <remarks/>
    deleted,
    
    /// <remarks/>
    skipped,
}
}
#pragma warning restore
