// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class AlbumID3
{
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Artist { get; set; }
        public string ArtistId { get; set; }
        public string CoverArt { get; set; }
        public int SongCount { get; set; }
        public int Duration { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Starred { get; set; }
        public int Year { get; set; }
        public string Genre { get; set; }
}
}
#pragma warning restore
