// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class ArtistWithAlbumsID3 : ArtistID3
{
    
        public List<AlbumID3> Album { get; set; }
    
    public ArtistWithAlbumsID3()
    {
        Album = new List<AlbumID3>();
    }
}
}
#pragma warning restore
