// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class ArtistInfo2 : ArtistInfoBase
{
    
        public List<ArtistID3> SimilarArtist { get; set; }
    
    public ArtistInfo2()
    {
        SimilarArtist = new List<ArtistID3>();
    }
}
}
#pragma warning restore
