// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class Bookmark
{
    
        public Child Entry { get; set; }
        public long Position { get; set; }
        public string Username { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Changed { get; set; }
    
    public Bookmark()
    {
        Entry = new Child();
    }
}
}
#pragma warning restore
