// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class ChatMessages
{
    
        public List<ChatMessage> ChatMessage { get; set; }
    
    public ChatMessages()
    {
        ChatMessage = new List<ChatMessage>();
    }
}
}
#pragma warning restore
