// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class ChatMessage
{
    
        public string Username { get; set; }
        public long Time { get; set; }
        public string Message { get; set; }
}
}
#pragma warning restore
