// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class Genre
{
    
        public int SongCount { get; set; }
        public int AlbumCount { get; set; }
        public List<string> Text { get; set; }
}
}
#pragma warning restore
