// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class Indexes
{
    
        public List<Artist> Shortcut { get; set; }
        public List<Index> Index { get; set; }
        public List<Child> Child { get; set; }
        public long LastModified { get; set; }
        public string IgnoredArticles { get; set; }
    
    public Indexes()
    {
        Child = new List<Child>();
        Index = new List<Index>();
        Shortcut = new List<Artist>();
    }
}
}
#pragma warning restore
