// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class IndexID3
{
    
        public List<ArtistID3> Artist { get; set; }
        public string Name { get; set; }
    
    public IndexID3()
    {
        Artist = new List<ArtistID3>();
    }
}
}
#pragma warning restore
