// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class JukeboxStatus
{
    
        public int CurrentIndex { get; set; }
        public bool Playing { get; set; }
        public float Gain { get; set; }
        public int Position { get; set; }
}
}
#pragma warning restore
