// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class License
{
    
        public bool Valid { get; set; }
        public string Email { get; set; }
        public string Key { get; set; }
        public System.DateTime Date { get; set; }
}
}
#pragma warning restore
