// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class NowPlayingEntry : Child
{
    
        public string Username { get; set; }
        public int MinutesAgo { get; set; }
        public int PlayerId { get; set; }
        public string PlayerName { get; set; }
}
}
#pragma warning restore
