// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class Playlists
{
    
        public List<Playlist> Playlist { get; set; }
    
    public Playlists()
    {
        Playlist = new List<Playlist>();
    }
}
}
#pragma warning restore
