// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class PlaylistWithSongs : Playlist
{
    
        public List<Child> Entry { get; set; }
    
    public PlaylistWithSongs()
    {
        Entry = new List<Child>();
    }
}
}
#pragma warning restore
