// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class PodcastChannel
{
    
        public List<PodcastEpisode> Episode { get; set; }
        public string Id { get; set; }
        public string Url { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public PodcastStatus Status { get; set; }
        public string ErrorMessage { get; set; }
    
    public PodcastChannel()
    {
        Episode = new List<PodcastEpisode>();
    }
}
}
#pragma warning restore
