// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class PodcastEpisode : Child
{
    
        public string StreamId { get; set; }
        public string Description { get; set; }
        public PodcastStatus Status { get; set; }
        public System.DateTime PublishDate { get; set; }
}
}
#pragma warning restore
