// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    public enum PodcastStatus
{
    
    /// <remarks/>
    @new,
    
    /// <remarks/>
    downloading,
    
    /// <remarks/>
    completed,
    
    /// <remarks/>
    error,
    
    /// <remarks/>
    deleted,
    
    /// <remarks/>
    skipped,
}
}
#pragma warning restore
