// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class Response
{
    
        public object Item { get; set; }
        public ItemChoiceType ItemElementName { get; set; }
        public ResponseStatus Status { get; set; }
        public string Version { get; set; }
}
}
#pragma warning restore
