// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class SearchResult
{
    
        public List<Child> Match { get; set; }
        public int Offset { get; set; }
        public int TotalHits { get; set; }
    
    public SearchResult()
    {
        Match = new List<Child>();
    }
}
}
#pragma warning restore
