// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class Share
{
    
        public List<Child> Entry { get; set; }
        public string Id { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public string Username { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Expires { get; set; }
        public System.DateTime LastVisited { get; set; }
        public int VisitCount { get; set; }
    
    public Share()
    {
        Entry = new List<Child>();
    }
}
}
#pragma warning restore
