// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class Shares
{
    
        public List<Share> Share { get; set; }
    
    public Shares()
    {
        Share = new List<Share>();
    }
}
}
#pragma warning restore
