// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Collections.Generic;
using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class Starred2
{
    
        public List<ArtistID3> Artist { get; set; }
        public List<AlbumID3> Album { get; set; }
        public List<Child> Song { get; set; }
    
    public Starred2()
    {
        Song = new List<Child>();
        Album = new List<AlbumID3>();
        Artist = new List<ArtistID3>();
    }
}
}
#pragma warning restore
