// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

#pragma warning disable
namespace Subsonic.Domain.API.API11
{
    [DebuggerStepThrough]
public partial class User
{
    
        public string Username { get; set; }
        public string Email { get; set; }
        public bool ScrobblingEnabled { get; set; }
        public bool AdminRole { get; set; }
        public bool SettingsRole { get; set; }
        public bool DownloadRole { get; set; }
        public bool UploadRole { get; set; }
        public bool PlaylistRole { get; set; }
        public bool CoverArtRole { get; set; }
        public bool CommentRole { get; set; }
        public bool PodcastRole { get; set; }
        public bool StreamRole { get; set; }
        public bool JukeboxRole { get; set; }
        public bool ShareRole { get; set; }
}
}
#pragma warning restore
