// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Subsonic.Domain.API.API12
{
    public enum MediaType
{
    
    /// <remarks/>
    music,
    
    /// <remarks/>
    podcast,
    
    /// <remarks/>
    audiobook,
    
    /// <remarks/>
    video,
}
}
#pragma warning restore
