// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.2.0.31
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Subsonic.Domain.API.API14
{
    public enum ResponseStatus
    {

        /// <remarks/>
        ok,

        /// <remarks/>
        failed,
    }
}
#pragma warning restore
